Title <- character()
Description <- character()
BiocVersion <- character()
Genome <- character()
SourceType <- character()
SourceUrl <- character()
SourceVersion  <- character()
Species <- character()
TaxonomyId <- character()
Coordinate_1_based <- logical()
DataProvider <- character()
Maintainer <- character()
RDataClass <- character()
DispatchClass <- character()
RDataPath <- character()
write.csv(data.frame(Title, Description, BiocVersion, Genome, SourceType, SourceUrl, SourceVersion, Species, TaxonomyId, Coordinate_1_based, DataProvider, Maintainer, RDataClass, DispatchClass, RDataPath), "inst/extdata/metadata.csv")
